---
apiVersion: v1
kind: Pod
metadata:
   name: tomcatapp
   labels:
     app: kube-pro

spec:
  containers:
     - name: tomcat-image
       image: tomcat:8.0
       ports:
         - name: kube-pro-port
           containerPort: 8080
