---
apiVersion: v1
kind: Pod
metadata:
   name: demo-shell

spec:
  containers:
     - name: demo-shell
       image: debian
       command: ["/bin/sh"]
       args: ["-c", "while true; do echo Hello; sleep 10; done"]
